// Copyright 2024 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#include "cmd_num_values.h"
#include "cmds.h"

static cmd_t commands[] =
{
 {0xff, "BIQUAD_LEFT_SHIFT", TYPE_INT32, CMD_BIQUAD_LEFT_SHIFT, CMD_READ_WRITE, NUM_VALUES_BIQUAD_LEFT_SHIFT, "add help string", false},
 {0xff, "BIQUAD_FILTER_COEFFS", TYPE_INT32, CMD_BIQUAD_FILTER_COEFFS, CMD_READ_WRITE, NUM_VALUES_BIQUAD_FILTER_COEFFS, "add help string", false},
 {0xff, "BIQUAD_RESERVED", TYPE_INT32, CMD_BIQUAD_RESERVED, CMD_READ_WRITE, NUM_VALUES_BIQUAD_RESERVED, "add help string", false},

 {0xff, "CASCADED_BIQUADS_LEFT_SHIFT", TYPE_INT32, CMD_CASCADED_BIQUADS_LEFT_SHIFT, CMD_READ_WRITE, NUM_VALUES_CASCADED_BIQUADS_LEFT_SHIFT, "add help string", false},
 {0xff, "CASCADED_BIQUADS_FILTER_COEFFS", TYPE_INT32, CMD_CASCADED_BIQUADS_FILTER_COEFFS, CMD_READ_WRITE, NUM_VALUES_CASCADED_BIQUADS_FILTER_COEFFS, "add help string", false},

 {0xff, "COMPRESSOR_RMS_ATTACK_ALPHA", TYPE_INT32, CMD_COMPRESSOR_RMS_ATTACK_ALPHA, CMD_READ_WRITE, NUM_VALUES_COMPRESSOR_RMS_ATTACK_ALPHA, "add help string", false},
 {0xff, "COMPRESSOR_RMS_RELEASE_ALPHA", TYPE_INT32, CMD_COMPRESSOR_RMS_RELEASE_ALPHA, CMD_READ_WRITE, NUM_VALUES_COMPRESSOR_RMS_RELEASE_ALPHA, "add help string", false},
 {0xff, "COMPRESSOR_RMS_ENVELOPE", TYPE_INT32, CMD_COMPRESSOR_RMS_ENVELOPE, CMD_READ_WRITE, NUM_VALUES_COMPRESSOR_RMS_ENVELOPE, "add help string", false},
 {0xff, "COMPRESSOR_RMS_THRESHOLD", TYPE_INT32, CMD_COMPRESSOR_RMS_THRESHOLD, CMD_READ_WRITE, NUM_VALUES_COMPRESSOR_RMS_THRESHOLD, "add help string", false},
 {0xff, "COMPRESSOR_RMS_GAIN", TYPE_INT32, CMD_COMPRESSOR_RMS_GAIN, CMD_READ_WRITE, NUM_VALUES_COMPRESSOR_RMS_GAIN, "add help string", false},
 {0xff, "COMPRESSOR_RMS_SLOPE", TYPE_FLOAT, CMD_COMPRESSOR_RMS_SLOPE, CMD_READ_WRITE, NUM_VALUES_COMPRESSOR_RMS_SLOPE, "add help string", false},

 {0xff, "DSP_THREAD_MAX_CYCLES", TYPE_UINT32, CMD_DSP_THREAD_MAX_CYCLES, CMD_READ_WRITE, NUM_VALUES_DSP_THREAD_MAX_CYCLES, "add help string", false},

 {0xff, "ENVELOPE_DETECTOR_PEAK_ATTACK_ALPHA", TYPE_INT32, CMD_ENVELOPE_DETECTOR_PEAK_ATTACK_ALPHA, CMD_READ_WRITE, NUM_VALUES_ENVELOPE_DETECTOR_PEAK_ATTACK_ALPHA, "add help string", false},
 {0xff, "ENVELOPE_DETECTOR_PEAK_RELEASE_ALPHA", TYPE_INT32, CMD_ENVELOPE_DETECTOR_PEAK_RELEASE_ALPHA, CMD_READ_WRITE, NUM_VALUES_ENVELOPE_DETECTOR_PEAK_RELEASE_ALPHA, "add help string", false},
 {0xff, "ENVELOPE_DETECTOR_PEAK_ENVELOPE", TYPE_INT32, CMD_ENVELOPE_DETECTOR_PEAK_ENVELOPE, CMD_READ_WRITE, NUM_VALUES_ENVELOPE_DETECTOR_PEAK_ENVELOPE, "add help string", false},

 {0xff, "ENVELOPE_DETECTOR_RMS_ATTACK_ALPHA", TYPE_INT32, CMD_ENVELOPE_DETECTOR_RMS_ATTACK_ALPHA, CMD_READ_WRITE, NUM_VALUES_ENVELOPE_DETECTOR_RMS_ATTACK_ALPHA, "add help string", false},
 {0xff, "ENVELOPE_DETECTOR_RMS_RELEASE_ALPHA", TYPE_INT32, CMD_ENVELOPE_DETECTOR_RMS_RELEASE_ALPHA, CMD_READ_WRITE, NUM_VALUES_ENVELOPE_DETECTOR_RMS_RELEASE_ALPHA, "add help string", false},
 {0xff, "ENVELOPE_DETECTOR_RMS_ENVELOPE", TYPE_INT32, CMD_ENVELOPE_DETECTOR_RMS_ENVELOPE, CMD_READ_WRITE, NUM_VALUES_ENVELOPE_DETECTOR_RMS_ENVELOPE, "add help string", false},

 {0xff, "FIXED_GAIN_GAIN", TYPE_INT32, CMD_FIXED_GAIN_GAIN, CMD_READ_WRITE, NUM_VALUES_FIXED_GAIN_GAIN, "add help string", false},

 {0xff, "LIMITER_PEAK_ATTACK_ALPHA", TYPE_INT32, CMD_LIMITER_PEAK_ATTACK_ALPHA, CMD_READ_WRITE, NUM_VALUES_LIMITER_PEAK_ATTACK_ALPHA, "add help string", false},
 {0xff, "LIMITER_PEAK_RELEASE_ALPHA", TYPE_INT32, CMD_LIMITER_PEAK_RELEASE_ALPHA, CMD_READ_WRITE, NUM_VALUES_LIMITER_PEAK_RELEASE_ALPHA, "add help string", false},
 {0xff, "LIMITER_PEAK_ENVELOPE", TYPE_INT32, CMD_LIMITER_PEAK_ENVELOPE, CMD_READ_WRITE, NUM_VALUES_LIMITER_PEAK_ENVELOPE, "add help string", false},
 {0xff, "LIMITER_PEAK_THRESHOLD", TYPE_INT32, CMD_LIMITER_PEAK_THRESHOLD, CMD_READ_WRITE, NUM_VALUES_LIMITER_PEAK_THRESHOLD, "add help string", false},
 {0xff, "LIMITER_PEAK_GAIN", TYPE_INT32, CMD_LIMITER_PEAK_GAIN, CMD_READ_WRITE, NUM_VALUES_LIMITER_PEAK_GAIN, "add help string", false},

 {0xff, "LIMITER_RMS_ATTACK_ALPHA", TYPE_INT32, CMD_LIMITER_RMS_ATTACK_ALPHA, CMD_READ_WRITE, NUM_VALUES_LIMITER_RMS_ATTACK_ALPHA, "add help string", false},
 {0xff, "LIMITER_RMS_RELEASE_ALPHA", TYPE_INT32, CMD_LIMITER_RMS_RELEASE_ALPHA, CMD_READ_WRITE, NUM_VALUES_LIMITER_RMS_RELEASE_ALPHA, "add help string", false},
 {0xff, "LIMITER_RMS_ENVELOPE", TYPE_INT32, CMD_LIMITER_RMS_ENVELOPE, CMD_READ_WRITE, NUM_VALUES_LIMITER_RMS_ENVELOPE, "add help string", false},
 {0xff, "LIMITER_RMS_THRESHOLD", TYPE_INT32, CMD_LIMITER_RMS_THRESHOLD, CMD_READ_WRITE, NUM_VALUES_LIMITER_RMS_THRESHOLD, "add help string", false},
 {0xff, "LIMITER_RMS_GAIN", TYPE_INT32, CMD_LIMITER_RMS_GAIN, CMD_READ_WRITE, NUM_VALUES_LIMITER_RMS_GAIN, "add help string", false},

 {0xff, "MIXER_GAIN", TYPE_INT32, CMD_MIXER_GAIN, CMD_READ_WRITE, NUM_VALUES_MIXER_GAIN, "add help string", false},

 {0xff, "NOISE_GATE_ATTACK_ALPHA", TYPE_INT32, CMD_NOISE_GATE_ATTACK_ALPHA, CMD_READ_WRITE, NUM_VALUES_NOISE_GATE_ATTACK_ALPHA, "add help string", false},
 {0xff, "NOISE_GATE_RELEASE_ALPHA", TYPE_INT32, CMD_NOISE_GATE_RELEASE_ALPHA, CMD_READ_WRITE, NUM_VALUES_NOISE_GATE_RELEASE_ALPHA, "add help string", false},
 {0xff, "NOISE_GATE_ENVELOPE", TYPE_INT32, CMD_NOISE_GATE_ENVELOPE, CMD_READ_WRITE, NUM_VALUES_NOISE_GATE_ENVELOPE, "add help string", false},
 {0xff, "NOISE_GATE_THRESHOLD", TYPE_INT32, CMD_NOISE_GATE_THRESHOLD, CMD_READ_WRITE, NUM_VALUES_NOISE_GATE_THRESHOLD, "add help string", false},
 {0xff, "NOISE_GATE_GAIN", TYPE_INT32, CMD_NOISE_GATE_GAIN, CMD_READ_WRITE, NUM_VALUES_NOISE_GATE_GAIN, "add help string", false},

 {0xff, "PIPELINE_CHECKSUM", TYPE_UINT8, CMD_PIPELINE_CHECKSUM, CMD_READ_WRITE, NUM_VALUES_PIPELINE_CHECKSUM, "add help string", false},

 {0xff, "SWITCH_POSITION", TYPE_INT32, CMD_SWITCH_POSITION, CMD_READ_WRITE, NUM_VALUES_SWITCH_POSITION, "add help string", false},

 {0xff, "VOLUME_CONTROL_TARGET_GAIN", TYPE_INT32, CMD_VOLUME_CONTROL_TARGET_GAIN, CMD_READ_WRITE, NUM_VALUES_VOLUME_CONTROL_TARGET_GAIN, "add help string", false},
 {0xff, "VOLUME_CONTROL_GAIN", TYPE_INT32, CMD_VOLUME_CONTROL_GAIN, CMD_READ_WRITE, NUM_VALUES_VOLUME_CONTROL_GAIN, "add help string", false},
 {0xff, "VOLUME_CONTROL_SLEW_SHIFT", TYPE_INT32, CMD_VOLUME_CONTROL_SLEW_SHIFT, CMD_READ_WRITE, NUM_VALUES_VOLUME_CONTROL_SLEW_SHIFT, "add help string", false},
 {0xff, "VOLUME_CONTROL_MUTE", TYPE_UINT8, CMD_VOLUME_CONTROL_MUTE, CMD_READ_WRITE, NUM_VALUES_VOLUME_CONTROL_MUTE, "add help string", false},

};
